sonar.organization=jbcom
sonar.projectKey=jbcom_extended-data
sonar.projectName=extended-data
sonar.sources=packages/extended-data/src,packages/pytest-extended-data/src
sonar.tests=packages/extended-data/tests,packages/pytest-extended-data/tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=docs/dist/**,docs/reference/generated/**
